summarization:
  model: google/gemma-7b-it
instruct:
  model: Qwen/Qwen3-Coder-30B-A3B-Instruct
instruct_python:
  model: Qwen/Qwen3-Coder-30B-A3B-Instruct
instruct_php:
  model: Qwen/Qwen3-Coder-30B-A3B-Instruct
instruct_javascript:
  model: Qwen/Qwen3-Coder-30B-A3B-Instruct