default:
  model: vision-novae
  control_net: qrCodeMonster
  negative_prompt: blurry
  guidance_scale: 7
  num_inference_steps: 25
  controlnet_conditioning_scale: 1.4
baroque:
  model: vision-novae
  control_net: qrCodeMonster
  guidance_scale: 7
  num_inference_steps: 25
  controlnet_conditioning_scale: 1.2
  prompt: >
    A RAW photo of Baroque rococo architecture, architectural photography, 
    post apocalyptic New York, hyperrealism, [roots], hyperrealistic, 
    octane render, cinematic, hyper detailed, 8K
  negative_prompt: blurry
castle:
  model: vision-novae
  control_net: qrCodeMonster
  guidance_scale: 7
  num_inference_steps: 25
  controlnet_conditioning_scale: 1.3
  scheduler_class: UniPCMultistepScheduler
  prompt: >
    RAW photo of an Medievil castle surrounded by water and nature, village, 
    volumetric lighting, photorealistic, insanely detailed and intricate,
    Fantasy, epic cinematic shot, trending on ArtStation, mountains, 
    8k ultra hd
  negative_prompt: blurry
landscape:
  model: dreamturbo
  control_net: qrCodeMonster
  guidance_scale: 2
  num_inference_steps: 10
  controlnet_conditioning_scale: 0.5
  prompt: >
    (masterpiece:1.2, best quality), (ultra-detailed), (illustration), 
    (ultra highres), (delicate illustration), (hyper-detailed), 
    (super detail:1.3), professional lighting, cinematic lighting, 
    (nostalgia and peacefulness:1.3), professional (landscape painting) of natures, 
    moon lighting, moon light on trees leaves, (dark cloud, dark night, full moon, dark lighting)
  negative_prompt: >
    human, man, woman, people, person, (worst quality:1.4), (low quality:1.4), 
    (EasyNegative:1.0), paintings, sketches, (normal quality:2), lowres, 
    normal quality, ((monochrome)), ((grayscale)), 
    jpeg artifacts, signature, watermark, username, 
    Multiple people, bad, text, error, ugly
tito:
  model: vision-novae
  control_net: qrCodeMonster
  guidance_scale: 7
  num_inference_steps: 30
  controlnet_conditioning_scale: 0.8
  clip_skip: 2
  prompt: >
    extremely detailed, best quality,beautiful lighting, 
    curtains,natural light,intricate details,realistic, 
    detailed face and eyes,wearing erotic lingerie,naughty negligee, 
    sexy nightie, looking at viewer
  negative_prompt: >
    BadDream, FastNegativeV2, signature,
    (leaning_against_wall:1.3), (hat:1.3), (umbrella:1.2), nsfw
food:
  model: dreamturbo
  control_net: qrCodeMonster
  guidance_scale: 2
  num_inference_steps: 12
  controlnet_conditioning_scale: 0.75
  clip_skip: 2
  prompt: >
    masterpiece, best quality,painting,anime coloring,artwork,illustration,huiguorou,Cylinder Pork Belly,food,no_humans,game cg,4k,8k,unity <lora:huiguorou6014b:1>
  negative_prompt: >
    lowres, extra digit, 
    fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, (worst quality:2), (low quality:2), 
    (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), 
    out of view, cut off, ugly, EasyNegative, paintings, sketches, (worst quality:2)
panda:
  model: vision-novae
  control_net: qrCodeMonster
  guidance_scale: 1.5
  num_inference_steps: 7
  controlnet_conditioning_scale: 0.7
  clip_skip: 2
  prompt: >
    male, anthro, (kfp_po:1.2), giant panda, two-tone fur, (shirtless, panda:1.1), 
    body fur, head tuft, green eyes, belt, brown shorts, seam (sewing), patch (fabric), 
    ragged shorts, chubby, smile, grin, one hand up, pawpads, claws, foot wraps, outdoors, 
    sitting, shrine, east asian architecture, (masterpiece, highly detailed:1.2), no humans,
    <lora:lorakfppov2-10:1>
  negative_prompt: >
    (Watermark:1.3), (easynegative:0.5), EasyNegativeV2, UnrealisticDream, BadDream, bad art, floating limb, fused hand, poorly drawn face, disfigured, cropped, floating limb, malformed, extra finger, deformed